### ISSUE TITLE
Wallpaper doesn't span correctly on my monitor configuration

### ISSUE THREAD

**Issue by spencermacca** [Pabilo8/forest-wallpaper#1]
Wallpaper doesn't span correctly on my 16:9 + 4:3 monitor setup. See below.
![ckLfWkATN0](https://user-images.githubusercontent.com/35679480/92667998-e3065e00-f350-11ea-87a4-3d9aef584a95.png)

**Comment by WolffRuoff** [comment]
I'm having this same issue on my 4k monitor using the lively release.

**Comment by jean3x7** [comment]
> I'm having this same issue on my 4k monitor using the lively release.

me too
